### ISSUE TITLE
Virus Warning

### ISSUE THREAD

**Issue by rkirman** [diogomartino/palworld-ds-gui#13]
Virus warning the moment the file hit my filesystem..
![image](https://github.com/diogomartino/palworld-ds-gui/assets/52388483/cff8c2aa-2414-48d3-9d85-1e5c4f4a9b9d)

**Comment by diogomartino** [comment]
Hi, that's a problem that I always had with projects like this. Windows doesn't like downloading unsigned executable straight from the internet. This specific one also has a really suspicious behavior since it downloads another .exe when you open it (which is SteamCMD), so that's always gonna get flagged by antivirus. From what I know, getting a certificate for the app costs a lot of money, so I'll not bother with that. So either you trust the app (you can always go through the code and see what it does) or if you are uncomfortable with it, don't use it. Nothing I can do about it...

**Comment by rkirman** [comment]
all good mate, just thought i'd let ya know..
happy with how easy it was to use.
