### ISSUE TITLE
nosteam param being ignored

### ISSUE THREAD

**Issue by aethervisor** [diogomartino/palworld-ds-gui#28]
Does not seem the -nosteam param works? works fine in 0.7. 
Upgrade to the new server-client version. Does not work.

**Comment by diogomartino** [comment]
Hi, that's strange, will take a look at that.

**Comment by diogomartino** [comment]
Found the issue, actually all params were being ignored. A new version will be released soon, thanks for the report!

**Comment by aethervisor** [comment]
Still doesn't seem to be working for me in new version.

**Comment by diogomartino** [comment]
Sorry, just found a new issue with the current implementation. The thing is, I don't have any way of testing if the params are actually doing anything. If you could test this for me to see if it fixes the issue that would be great.

The code is in #32 if you want to check the code or build it yourself, otherwise I attached the binary here.

[serverfix-params.zip](https://github.com/diogomartino/palworld-ds-gui/files/14514653/serverfix-params.zip)
