### ISSUE TITLE
Could you also get the web interface via the exe?

### ISSUE THREAD

**Issue by BoergiM87** [diogomartino/palworld-ds-gui#4]
Hello, can you also get a web service when you start the EXE so that you can also open the GUI via the browser?

**Comment by diogomartino** [comment]
Wails in development mode does that out of the box, not sure if I can enable it in production builds (probably not). However if I go ahead and implement #2 that would probably be an out of the box experience. I'll see what I can do about it, thanks for the feedback!

**Comment by BoergiM87** [comment]
Hey I have tried the dev mode... but the web version is black and nothing is displayed. Do you have any idea why? I don't know much about Wails

**Comment by diogomartino** [comment]
I personally never use the browser, so I didn't try it before. The black screen is a known issue for me since it happens in the app as well. The logs show that there's something wrong with the event listeners, but I'm not sure what. It's probably a bug with Wails. This doesn't bother me too much because if I restart the app everything comes back (when not in the browser). Tried in the browser and in Chrome and Edge that black screen always happens. In Firefox it works as expected, which is being stuck in the Initializing screen because the go app is not ready to have multiple interfaces running at the same time. To overcome this you can simply add a line of code and everything should work:

Open the `app.go` and in the line 47 add:

```go
runtime.EventsEmit(a.ctx, "SET_LOADING_STATUS", "DONE")
```

![image](https://github.com/diogomartino/palworld-ds-gui/assets/16502356/9c74714d-3f66-490e-80c7-3c9a178d3c30)

So, if you add this line and use Firefox you should be good to go!
If you want to use it in the browser you'll need to do that, I don't have plans to officially support it in the near future.
